services:
  # 1. The Valhalla Routing Engine (Docker)
  - type: web
    name: bus-tracker-valhalla
    env: docker
    rootDir: bus_tracker_v2/valhalla-server
    plan: free

  # 2. The FastAPI Backend (Python)
  - type: web
    name: bus-tracker-backend
    env: python
    rootDir: bus_tracker_v2/backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT"
    envVars:
      - key: VALHALLA_URL
        value: "https://bus-tracker-valhalla.onrender.com"
      - key: PYTHON_VERSION
        value: "3.11.0"
    plan: free
